name: html_to_markdown_rust_benchmarks
description: Benchmarks comparing html_to_markdown_rust with html2md
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  benchmark_harness: ^2.4.0
  html2md: ^1.3.2
  html_to_markdown_rust:
    path: ../

dev_dependencies:
  lints: ^6.0.0
